name: Siap To The Moon or Lower Earth

on:
  workflow_dispatch: # Mengaktifkan tombol manual di dashboard GitHub
  schedule:
    # Berjalan otomatis setiap Senin-Jumat jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * 1-5'
    # Berjalan otomatis setiap Senin-Jumat jam 09:00 UTC (16:00 WIB)
    - cron: '0 9 * * 1-5'

jobs:
  scan-market:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        uses: actions/checkout@v4

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Pustaka Analisis Saham
        run: |
          pip install requests yfinance pandas numpy

      - name: Jalankan ABO Scanner Massal
        run: python main.py
