name: Sinyal Saham Sideways Harian

on:
  schedule:
    - cron: '30 9 * * 1-5'
  workflow_dispatch:

jobs:
  scan-market:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Requests Library
      run: pip install requests

    - name: Jalankan ABO Scanner Massal
      run: |
        # Jalankan langsung di folder utama tanpa pindah tempat agar semua file terbaca sempurna
        python jalan_radar.py
